export default {
    CREATE_COURSE: "CREATE_COURSE_SUCCESS",
    LOAD_COURSES: "LOAD_COURSES_SUCCESS",
    UPDATE_COURSE: "UPDATE_COURSE_SUCCESS",
    DELETE_COURSE: "DELETE_COURSE_SUCCESS",
    LOAD_AUTHORS: "LOAD_AUTHORS_SUCCESS",
    BEGIN_API_CALL: "BEGIN_API_CALL"
};