/* eslint-disable import/no-anonymous-default-export */
export default {
    CREATE_COURSE_SUCCESS: "CREATE_COURSE_SUCCESS",
    LOAD_COURSES_SUCCESS: "LOAD_COURSES_SUCCESS",
    UPDATE_COURSE_SUCCESS: "UPDATE_COURSE_SUCCESS",
    DELETE_COURSE_SUCCESS: "DELETE_COURSE_SUCCESS",
    LOAD_AUTHORS_SUCCESS: "LOAD_AUTHORS_SUCCESS",
    BEGIN_API_CALL: "BEGIN_API_CALL",
    API_CALL_ERROR: "API_CALL_ERROR",
    DELETE_COURSE_OPTIMISTIC: "DELETE_COURSE_OPTIMISTIC",
};